/* Generated by startup_generator */

#include <stm32f30x.h>

extern void _estack(void);  // to force type checking
void Reset_Handler(void);
void default_handler (void) { while(1); }

void __attribute__ ((weak)) __libc_init_array(void){}

// Linker supplied pointers

extern unsigned long _sidata;
extern unsigned long _sdata;
extern unsigned long _edata;
extern unsigned long _sbss;
extern unsigned long _ebss;

extern int main(void);

void Reset_Handler(void) {

   unsigned long *src, *dst;

   src = &_sidata;
   dst = &_sdata;

   // Copy data initializers

    while (dst < &_edata)
      *(dst++) = *(src++);

   // Zero bss

   dst = &_sbss;
   while (dst < &_ebss)
       *(dst++) = 0;

  SystemInit();
  __libc_init_array();
  main();
  while(1) {}
}

/* Vector Table */

void NMI_Handler (void) __attribute__ ((weak,  alias ("default_handler")));
void HardFault_Handler (void) __attribute__ ((weak,  alias ("default_handler")));
void MemMange_Handler (void) __attribute__ ((weak,  alias ("default_handler")));
void BusFault_Handler (void) __attribute__ ((weak,  alias ("default_handler")));
void UsageFault_Handler (void) __attribute__ ((weak,  alias ("default_handler")));
void SVC_Handler (void) __attribute__ ((weak,  alias ("default_handler")));
void DebugMon_Handler (void) __attribute__ ((weak,  alias ("default_handler")));
void PendSV_Handler (void) __attribute__ ((weak,  alias ("default_handler")));
void SysTick_Handler (void) __attribute__ ((weak,  alias ("default_handler")));
void WWDG_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void PVD_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TAMPER_STAMP_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void RTC_WKUP_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void FLASH_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void RCC_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void EXTI0_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void EXTI1_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void EXTI2_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void EXTI3_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void EXTI4_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void DMA1_Channel1_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void DMA1_Channel2_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void DMA1_Channel3_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void DMA1_Channel4_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void DMA1_Channel5_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void DMA1_Channel6_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void DMA1_Channel7_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void ADC1_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void CAN1_TX_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void CAN1_RX0_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void CAN1_RX1_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void CAN1_SCE_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void EXTI9_5_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM1_BRK_TIM15_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM1_UP_TIM16_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM1_TRG_COM_TIM17_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM1_CC_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM2_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM3_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM4_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void I2C1_EV_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void I2C1_ER_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void I2C2_EV_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void I2C2_ER_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void SPI1_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void SPI2_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void USART1_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void USART2_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void USART3_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void EXTI15_10_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void RTC_Alarm_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void CEC_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM12_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM13_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM14_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void ADC3_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void FSMC_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void SDIO_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM5_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void SPI3_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void UART4_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void UART5_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM6_DAC_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void TIM7_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void DMA2_Channel1_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void DMA2_Channel2_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void DMA2_Channel3_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void DMA2_Channel4_5_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void DMA2_Channel5_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void ETH_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void ETH_WKUP_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void CAN2_TX_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void CAN2_RX0_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void CAN2_RX1_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void CAN2_SCE_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));
void OTG_FS_IRQHandler (void) __attribute__ ((weak,  alias ("default_handler")));



__attribute__ ((section(".isr_vector")))

void (* const g_pfnVectors[])(void) = {
  [0]  = _estack,
  [1]  = Reset_Handler,
  [2]  = NMI_Handler,
  [3]  = HardFault_Handler,
  [4]  = MemMange_Handler,
  [5]  = BusFault_Handler,
  [6]  = UsageFault_Handler,
  [11] = SVC_Handler,
  [12] = DebugMon_Handler,
  [14] = PendSV_Handler,
  [15] = SysTick_Handler,
  [16] = WWDG_IRQHandler,
  [17] = PVD_IRQHandler,
  [18] = TAMPER_STAMP_IRQHandler,
  [19] = RTC_WKUP_IRQHandler,
  [20] = FLASH_IRQHandler,
  [21] = RCC_IRQHandler,
  [22] = EXTI0_IRQHandler,
  [23] = EXTI1_IRQHandler,
  [24] = EXTI2_IRQHandler,
  [25] = EXTI3_IRQHandler,
  [26] = EXTI4_IRQHandler,
  [27] = DMA1_Channel1_IRQHandler,
  [28] = DMA1_Channel2_IRQHandler,
  [29] = DMA1_Channel3_IRQHandler,
  [30] = DMA1_Channel4_IRQHandler,
  [31] = DMA1_Channel5_IRQHandler,
  [32] = DMA1_Channel6_IRQHandler,
  [33] = DMA1_Channel7_IRQHandler,
  [34] = ADC1_IRQHandler,
  [35] = CAN1_TX_IRQHandler,
  [36] = CAN1_RX0_IRQHandler,
  [37] = CAN1_RX1_IRQHandler,
  [38] = CAN1_SCE_IRQHandler,
  [39] = EXTI9_5_IRQHandler,
  [40] = TIM1_BRK_TIM15_IRQHandler,
  [41] = TIM1_UP_TIM16_IRQHandler,
  [42] = TIM1_TRG_COM_TIM17_IRQHandler,
  [43] = TIM1_CC_IRQHandler,
  [44] = TIM2_IRQHandler,
  [45] = TIM3_IRQHandler,
  [46] = TIM4_IRQHandler,
  [47] = I2C1_EV_IRQHandler,
  [48] = I2C1_ER_IRQHandler,
  [49] = I2C2_EV_IRQHandler,
  [50] = I2C2_ER_IRQHandler,
  [51] = SPI1_IRQHandler,
  [52] = SPI2_IRQHandler,
  [53] = USART1_IRQHandler,
  [54] = USART2_IRQHandler,
  [55] = USART3_IRQHandler,
  [56] = EXTI15_10_IRQHandler,
  [57] = RTC_Alarm_IRQHandler,
  [58] = CEC_IRQHandler,
  [59] = TIM12_IRQHandler,
  [60] = TIM13_IRQHandler,
  [61] = TIM14_IRQHandler,
  [63] = ADC3_IRQHandler,
  [64] = FSMC_IRQHandler,
  [65] = SDIO_IRQHandler,
  [66] = TIM5_IRQHandler,
  [67] = SPI3_IRQHandler,
  [68] = UART4_IRQHandler,
  [69] = UART5_IRQHandler,
  [70] = TIM6_DAC_IRQHandler,
  [71] = TIM7_IRQHandler,
  [72] = DMA2_Channel1_IRQHandler,
  [73] = DMA2_Channel2_IRQHandler,
  [74] = DMA2_Channel3_IRQHandler,
  [75] = DMA2_Channel4_5_IRQHandler,
  [76] = DMA2_Channel5_IRQHandler,
  [77] = ETH_IRQHandler,
  [78] = ETH_WKUP_IRQHandler,
  [79] = CAN2_TX_IRQHandler,
  [80] = CAN2_RX0_IRQHandler,
  [81] = CAN2_RX1_IRQHandler,
  [82] = CAN2_SCE_IRQHandler,
  [83] = OTG_FS_IRQHandler,
};
